import Foundation

/// ChatGPT subscription limits reported by the official Codex client. These are
/// the returned Codex buckets, not a quota for every feature on chatgpt.com.
public struct CodexUsageProvider: UsageProvider {
    public let id = "chatgpt-codex"
    public let displayName = "ChatGPT · Codex"
    public let authMethod: AuthMethod = .keychainOAuth
    public let capabilities: Capabilities = [.usagePct, .resetTimer]
    public let refreshInterval: TimeInterval = 60

    private let client: CodexAppServerClient

    public init(client: CodexAppServerClient = CodexAppServerClient()) {
        self.client = client
    }

    public func fetch() async throws -> [UsageMetric] { try await client.fetch() }

    /// The schema is generated by `codex-cli 0.150.1`. Ignore new fields but keep
    /// absent windows absent and unknown duration/reset distinct from zero.
    static func parse(_ data: Data) throws -> [UsageMetric] {
        struct Window: Decodable {
            let usedPercent: Double
            let windowDurationMins: Int?
            let resetsAt: Int64?
        }
        struct Bucket: Decodable {
            let limitId: String?
            let limitName: String?
            let primary: Window?
            let secondary: Window?
        }
        struct Response: Decodable {
            let rateLimits: Bucket
            let rateLimitsByLimitId: [String: Bucket]?
        }
        let response: Response
        do { response = try JSONDecoder().decode(Response.self, from: data) }
        catch { throw CodexClientError.protocolFailure }

        let buckets: [(String, Bucket)]
        if let multiple = response.rateLimitsByLimitId, !multiple.isEmpty {
            buckets = multiple.keys.sorted().map { ($0, multiple[$0]!) }
        } else {
            buckets = [(response.rateLimits.limitId ?? "codex", response.rateLimits)]
        }
        var result: [UsageMetric] = []
        for (key, bucket) in buckets {
            let displayName = bucket.limitName.flatMap { $0.isEmpty ? nil : $0 } ?? key
            let name = displayName.caseInsensitiveCompare(key) == .orderedSame ? displayName : "\(displayName) (\(key))"
            for (position, window) in [("Primary", bucket.primary), ("Secondary", bucket.secondary)] {
                guard let window else { continue }
                guard window.usedPercent.isFinite, window.usedPercent >= 0,
                      window.windowDurationMins.map({ $0 > 0 }) ?? true,
                      window.resetsAt.map({ $0 >= 0 }) ?? true else {
                    throw CodexClientError.protocolFailure
                }
                let duration: String
                if let minutes = window.windowDurationMins {
                    if minutes % 1_440 == 0 { duration = "\(minutes / 1_440)-day" }
                    else if minutes % 60 == 0 { duration = "\(minutes / 60)-hour" }
                    else { duration = "\(minutes)-minute" }
                } else { duration = position }
                result.append(UsageMetric(
                    label: "\(name) · \(duration)", pct: window.usedPercent,
                    resetAt: window.resetsAt.map { Date(timeIntervalSince1970: Double($0)) },
                    providerId: "chatgpt-codex", windowDurationMinutes: window.windowDurationMins
                ))
            }
        }
        return result
    }
}
